### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by chrisgacsal** [jsontypedef/jsontypedef.com#22]
No A records for `jsontypedef.com`.

```shell
$ dig jsontypedef.com

; <<>> DiG 9.10.6 <<>> jsontypedef.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 25942
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;jsontypedef.com.		IN	A

;; Query time: 79 msec
;; SERVER: 10.10.11.254#53(10.10.11.254)
;; WHEN: Wed Feb 14 10:38:08 CET 2024
;; MSG SIZE  rcvd: 33
```

**Comment by chrisgacsal** [comment]
It seems that the `jsontypedef.com` domain subscription has been expired:
``` $ whois jsontypedef.com
...
Updated Date: 2024-02-13T04:16:22Z
Creation Date: 2020-02-12T03:08:51Z
Registrar Registration Expiration Date: 2024-02-12T04:08:51Z
...
```

**Comment by chrisgacsal** [comment]
@firede @ucarion @justinpowers ping

**Comment by ukstv** [comment]
This is sad.

**Comment by docktermj** [comment]
I'm hoping the project is alive and well.   We've started using it for https://github.com/senzing-garage/g2-sdk-json-type-definition

**Comment by ucarion** [comment]
Sorry folks, this was an administrative mistake. I expect this issue to be resolved soon, once DNS can repropagate.

**Comment by ucarion** [comment]
There are few things required to keep a specification alive -- keeping the online documentation posted being one of them. I've been distracted with work and didn't pay enough attention here.

**Comment by docktermj** [comment]
@ucarion I'm just happy that this site is alive and well.  You are doing good work here.

**Comment by ucarion** [comment]
The website has been up for me for at least 12 hours, so I'm inclined to think this issue is resolved. Closing this out.

Thanks all for the pings!
