### ISSUE TITLE
Genuinely human-readable validation errors

### ISSUE THREAD

**Issue by hdgarrood** [jsontypedef/jsontypedef.com#5]
Hi! I'm really liking the look of JTD so far, thanks for creating it! Sorry if this is the wrong place to ask, please do let me know if there's a more appropriate place for this question.

I read https://jsontypedef.com/docs/validation-errors/ and while I am sold on the approach, I do think it's a bit of a stretch to describe, e.g.
```
{"instancePath":"/foo/bar","schemaPath":"/definitions/bar"}
```
as "human-readable". I think it's also slightly problematic that the reason why the instance failed to validate against the schema is lost: you still have to refer to both the schema and the instance to figure out what the exact problem is. For example, suppose the above error was generated from a schema
```json
{
  "definitions": {
    "bar": { "type": "float64" }
  },
  "properties": {
    "foo": {
      "properties": {
        "bar": { "ref": "bar" }
      }
    }
  }
}
```
then, both of the following instances produce the same error:
```
{"foo":{"bar": "hello"}}
{"foo":{"bar": []}}
```
Is there any implementation which can produce more helpful error messages, such as:
```
At the path "/foo/bar": expected float64, found (string|array|whatever)
```
or alternatively, any interest in extending the specification in such a way that referring back to both the schema and the instance in order to generate such error messages is not necessary?

**Comment by ucarion** [comment]
I agree that it's a stretch, on a common reading of "human readable". The term "human readable" in that sentence is meant to contrast with "machine-readable".

I don't know of any such implementation out there, but as you suggest, one could be written. Given a set of errors, the instance, and the schema, it ought in most cases to be possible to generate validation messages that are in "plain English". But whether the message is helpful enough depends on the use-case.

I have never needed such a human-friendly validation error thing in production, so I haven't taken on this problem. I don't, for instance, have a good grip on how to handle the customization people may want, the question of whether to generate plain strings versus markup (HTML, etc.), and how to handle internationalization. I would expect that for progress to be made in this area, the first step is for someone to take a stab at doing this with JTD as-is, and figure out what is and isn't possible with the current specification.

I could imagine an extension to JTD that allowed for "context-free" validation strings, but the challenge is that the required context for a "human-friendly" validation message depends on the messages you want to produce. Having a real-world implementation would help clarify exactly what context is lacking in messages today, and what additional context can do.

**Comment by hdgarrood** [comment]
I've just realised that ajv includes exactly the kind of extension I was wondering about. For example, it can produce errors such as:
```
  {
    instancePath: '/baz/tag',
    schemaPath: '/properties/baz/mapping',
    keyword: 'discriminator',
    params: { error: 'mapping', tag: 'tag', tagValue: 'asdf' },
    message: 'value of tag "tag" must be in mapping'
  }
```
or
```
  {
    instancePath: '/foo/bar',
    schemaPath: '/definitions/bar/type',
    keyword: 'type',
    params: { type: 'float64', nullable: false },
    message: 'must be float64'
  }
```
I think the `keyword` and `params` properties provide enough information to deduce what kind of problem you have, and the `message` property is just there as a convenience for English speakers, but it seems like you could reconstruct the `message` property given the information in the `keyword` and `params` properties.

**Comment by ucarion** [comment]
That's good that AJV already does what you need. My take on this is that it's better to let relatively nimble projects, like AJV, to implement useful extensions on top of the relatively lumbering JTD IETF standard, which can only be updated on the order of once every few years.

Do you feel that something like AJV's extensions need to be "blessed" in some way? I see no harm in letting AJV have custom extensions for generating English convenience messages, while the JTD standard itself doesn't take on that problem.

**Comment by hdgarrood** [comment]
Nope, I don’t see any problem with that! Im not sure how relevant this is to the question of “blessing” an extension to the error message format, but I’ve noticed that the Rust implementation used in the jtd-validate tool gives really nice errors when the schema is invalid but invalid instances only give you a schemaPath and an instancePath (as the spec says), whereas AJV gives more useful errors when the instance is invalid but its errors when the schema is invalid are not very helpful. From my perspective (that is, someone trying to get some people to agree on a JSON data format which is based on JTD) it would be nice if there was a tool that could generate the best errors in both cases, so maybe I should just roll my sleeves up and start contributing.

**Comment by hdgarrood** [comment]
I’ll close this for now then. Thanks for the discussion!
